name: libexif_example
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'

dependencies:
  ffi: any
  libexif: any
  libjpeg: any

dependency_overrides:
  libexif:
    path: ..
  libjpeg:
    path: ../../libjpeg
